name: Secret scan

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  detect-secrets:
    name: Detect secrets
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: pre-commit/action@v3.0.1
